### ISSUE TITLE
swap excerpt and description

### ISSUE THREAD

**Issue by BarryThePenguin** [unifiedjs/unified-engine-atom#14]
I potentially got excerpt and description the wrong way around...

The linter [message docs](https://github.com/steelbrain/linter/blob/master/docs/types/linter-message-v2.md) state that `excerpt` is the `Error message` and `description` is the `Markdown long description of the error`

The [migration guide](https://github.com/steelbrain/linter/blob/master/docs/guides/upgrading-to-standard-linter-v2.md) mentions the changes where

- `text` is renamed to `excerpt`
- `html` is no longer allowed, similar functionality is available as `description`

Another confusing part is [`linter-ui-default`](https://github.com/steelbrain/linter-ui-default/blob/9f2680f50c40fc634789dc741b9026a35e2b9609/lib/panel/component.js#L54-L59) has `excerpt` as the key for the `Description` column in the Table output, and doesn't make mention on `description`.

Might need to clarify first somehow...

**Comment by wooorm** [comment]
Yeah, I noticed! I asked some questions [here](https://github.com/steelbrain/linter-ui-default/issues/205).
